"""Add event_data to TelemetryEvent

Revision ID: 6138e7912d84
Revises: aee49efe54c5
Create Date: 2026-08-18 03:11:07.822462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6138e7912d84'
down_revision: Union[str, Sequence[str], None] = 'aee49efe54c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_events', sa.Column('event_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_events', 'event_data')
    # ### end Alembic commands ###
