"""Initial schema and users

Revision ID: aee49efe54c5
Revises: 
Create Date: 2026-08-18 02:44:44.474109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee49efe54c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('experiment_type', sa.String(), nullable=True),
    sa.Column('baseline', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('hardware_profile', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiments_experiment_type'), 'experiments', ['experiment_type'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('authorisation_status', sa.String(), nullable=True),
    sa.Column('risk_classification', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_family'), 'samples', ['family'], unique=False)
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    op.create_index(op.f('ix_samples_sha256'), 'samples', ['sha256'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('experiment_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_metrics_metric_name'), 'experiment_metrics', ['metric_name'], unique=False)
    op.create_table('sandbox_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('vm_id', sa.String(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('isolation_status', sa.String(), nullable=True),
    sa.Column('analyst_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_runs_id'), 'sandbox_runs', ['id'], unique=False)
    op.create_index(op.f('ix_sandbox_runs_status'), 'sandbox_runs', ['status'], unique=False)
    op.create_table('attck_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=True),
    sa.Column('technique_name', sa.String(), nullable=True),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=True),
    sa.Column('heuristic_confidence', sa.Float(), nullable=True),
    sa.Column('genai_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sandbox_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attck_mappings_technique_id'), 'attck_mappings', ['technique_id'], unique=False)
    op.create_table('behavioural_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('feature_value', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_events', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sandbox_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioural_features_feature_name'), 'behavioural_features', ['feature_name'], unique=False)
    op.create_table('genai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('retrieved_context_ids', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('hallucination_check', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sandbox_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heuristic_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('cumulative_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('triggered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sandbox_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heuristic_scores_rule_id'), 'heuristic_scores', ['rule_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('generated_content', sa.JSON(), nullable=True),
    sa.Column('evidence_references', sa.JSON(), nullable=True),
    sa.Column('generation_model', sa.String(), nullable=True),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sandbox_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('parent_process_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('raw_event_hash', sa.String(), nullable=True),
    sa.Column('encrypted_payload_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sandbox_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_event_type'), 'telemetry_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_timestamp'), 'telemetry_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_timestamp'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event_type'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_table('reports')
    op.drop_index(op.f('ix_heuristic_scores_rule_id'), table_name='heuristic_scores')
    op.drop_table('heuristic_scores')
    op.drop_table('genai_analyses')
    op.drop_index(op.f('ix_behavioural_features_feature_name'), table_name='behavioural_features')
    op.drop_table('behavioural_features')
    op.drop_index(op.f('ix_attck_mappings_technique_id'), table_name='attck_mappings')
    op.drop_table('attck_mappings')
    op.drop_index(op.f('ix_sandbox_runs_status'), table_name='sandbox_runs')
    op.drop_index(op.f('ix_sandbox_runs_id'), table_name='sandbox_runs')
    op.drop_table('sandbox_runs')
    op.drop_index(op.f('ix_experiment_metrics_metric_name'), table_name='experiment_metrics')
    op.drop_table('experiment_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_samples_sha256'), table_name='samples')
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_family'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_experiments_experiment_type'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
